services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_mongo
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - mongodb-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_mongo
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=frodo
      - GF_SECURITY_ADMIN_PASSWORD=bolson
    depends_on:
      - prometheus
